
all:
	@cd vio;     make
	@cd audio;   make
	@cd awb_online_calibration; make
	@cd hifb;    make
	@cd lsc_online_cali; make
	@cd region;    make
	@cd tde;     make
	@cd venc;    make
#	@cd svp;     make
clean:
	@cd vio;     make clean
	@cd audio;   make clean
	@cd awb_online_calibration; make clean
	@cd hifb;    make clean
	@cd lsc_online_cali; make clean
	@cd region;  make clean
	@cd tde;     make clean
	@cd venc;    make clean
#	@cd svp;     make clean


