#!/bin/bash

TOPDIR=`pwd`
INSTALL_PATH=$TOPDIR/install
cd $INSTALL_PATH

CONFIG_FILE="config.sh"
source $CONFIG_FILE

RETVAL=$?
if [ $RETVAL -ne 0 ]; then
    exit 1;
fi

echo "PKG_DIRNAME:"$PKG_DIRNAME

UPGRADE_SCRIPT_FILE="upgrade.sh"

tar -cvf $PKG_TAR_FILENAME $PKG_DIRNAME

md5sum $PKG_TAR_FILENAME | awk '{printf $1"\n"}' > $PKG_HASHI_FILENAME

cat $UPGRADE_SCRIPT_FILE $PKG_HASHI_FILENAME $PKG_TAR_FILENAME > $PKG_FINAL_FILENAME
#cat $PKG_HASHI_FILENAME $PKG_TAR_FILENAME > $PKG_FINAL_FILENAME
chmod -R +x $INSTALL_PATH