#!/bin/sh

TOPDIR=`pwd`
INSTALL_PATH=$TOPDIR/install
APP_PATH=$TOPDIR/demo
HILINK_CONFIG_PATH=$TOPDIR/config
PKG_DIRNAME=pkg

PKG_TAR_FILENAME=upgrade.tar
PKG_FINAL_FILENAME=upgrade.bin
PKG_HASHI_FILENAME=hash.txt

#start
UPGRADE_SCRIPT_FILE="$INSTALL_PATH/upgrade.sh"
APP_FILE="$APP_PATH/hilinkapp"
HILINK_CONFIG_FILE="$HILINK_CONFIG_PATH/hilink.cfg"
HILINK_BAK_CONFIG_FILE="$HILINK_CONFIG_PATH/hilink_bak.cfg"

UPGRADE_FILE="$APP_FILE $HILINK_CONFIG_FILE $HILINK_BAK_CONFIG_FILE"

echo $UPGRADE_FILE

#end

cd $INSTALL_PATH
rm -f $PKG_TAR_FILENAME $PKG_HASHI_FILENAME $PKG_FINAL_FILENAME
rm -rf $PKG_DIRNAME/*
mkdir -p $PKG_DIRNAME
cp -rf $UPGRADE_FILE $PKG_DIRNAME/

RETVAL=$?
if [ $RETVAL -ne 0 ]; then
    exit 1;
fi

tar -cvf $PKG_TAR_FILENAME $PKG_DIRNAME

md5sum $PKG_TAR_FILENAME | awk '{printf $1"\n"}' > $PKG_HASHI_FILENAME

cat $UPGRADE_SCRIPT_FILE $PKG_HASHI_FILENAME $PKG_TAR_FILENAME > $PKG_FINAL_FILENAME
#cat $PKG_HASHI_FILENAME $PKG_TAR_FILENAME > $PKG_FINAL_FILENAME
chmod -R 777 $INSTALL_PATH