#ifndef _TYZIGBEEZCL3_H_
#define _TYZIGBEEZCL3_H_

#ifdef __cplusplus
extern "C"
{
#endif

    //ZCL3.0
    enum ZclCommandFrame
    {
        READ_ATTRIBUTE = 0X00,
        READ_ATTRIBUTES_RESPONSE = 0X01,
        WRITE_ATTRIBUTES = 0X02,
        WRITE_ATTRIBUTES_UNDIVIDED = 0X03,
        WRITE_ATTRIBUTES_RESPONSE = 0X04,
        WRITE_ATTRIBUTES_NO_RESPONSE = 0X05,
        CONFIGURE_REPORTING = 0X06,
        CONFIGURE_REPORTING_RESPONSE = 0X07,
        READ_REPORTING_CONFIGURATION = 0X08,
        READ_REPORTING_CONFIGURATION_RESPONSE = 0X09,
        REPORT_ATTRIBUTES = 0X0a,
        DEFAULT_RESPONSE = 0X0b,
        DISCOVER_ATTRIBUTES,
        DISCOVER_ATTRIBUTES_RESPONSE,
        READ_ATTRIBUTES_STRUCTURED,
        WRITE_ATTRIBUTES_STRUCTURED,
        WRITE_ATTRIBUTES_STRUCTURED_RESPONSE,
        DISCOVER_COMMANDS_RECEIVED,
        DISCOVER_COMMANDS_RECEIVED_RESPONSE,
        DISCOVER_COMMANDS_GENERATED,
        DISCOVER_COMMANDS_GENERATED_RESPONSE,
        DISCOVER_ATTRIBUTES_EXTENDED,
        DISCOVER_ATTRIBUTES_EXTENDED_RESPONSE
    };
    enum ZclClusterId
    {
        CLUSTERS_ID_BASIC = 0x0000,
        CLUSTERS_ID_IDENTIFY = 0x0003,
        CLUSTERS_ID_GROUP = 0x0004,
        CLUSTERS_ID_SCENE = 0x0005,
        CLUSTERS_ID_ON_OFF = 0x0006,
        CLUSTERS_ID_CUSTOM_DATA = 0xef00,
        CLUSTERS_ID_LIGHT_LEVEL = 0x0008,
        CLUSTERS_ID_LIGHT_COLOR_CTRL = 0x0300,
        CLUSTERS_ID_IAS_ZONE = 0x0500,
    };
    enum ZclBasicCluster
    {
        ATTRIBUTE_ID_ZCL_VERSION_ID = 0x0000,
        ATTRIBUTE_ID_APP_VERSION_ID = 0x0001,
        ATTRIBUTE_ID_STACK_VERSION_ID = 0x0002,
        ATTRIBUTE_ID_HW_VERSION_ID = 0x0003,
        ATTRIBUTE_ID_MANUFACTORY_NAME_ID = 0x0004,
        ATTRIBUTE_ID_MODELID_ID = 0x0005,
    };
    enum ZclOnoffCluster
    {
        ATTRIBUTE_ID_ON_OFF = 0x0000,
        ATTRIBUTE_ID_ON_TIME = 0x4001,
        ATTRIBUTE_ID_OFF_WAITE_TIME = 0x4002,
        ATTRIBUTE_ID_CLUSTER_REVSION = 0xfffd,
        ATTRIBUTE_ID_BACK_LIGHT = 0x5000,
        ATTRIBUTE_ID_CHILD_LOCK = 0x8000,
        ATTRIBUTE_ID_LED_MODE = 0x8001,
        ATTRIBUTE_ID_POWER_MEM = 0x8002,
        ATTRIBUTE_ID_OVER_CURRENT_ALARM = 0x8003,
        ATTRIBUTE_ID_DEVICE_TYOE = 0x8004,
    };

    enum ZCL_DATA_TYPE
    {
        ZCL_DATA_TYPE_NO_DATA = 0x00,
        ZCL_DATA_TYPE_8_BIT_DATA = 0x08,
        ZCL_DATA_TYPE_16_BIT_DATA = 0x09,
        ZCL_DATA_TYPE_24_BIT_DATA = 0x0a,
        ZCL_DATA_TYPE_32_BIT_DATA = 0x0b,
        ZCL_DATA_TYPE_40_BIT_DATA = 0x0c,
        ZCL_DATA_TYPE_48_BIT_DATA = 0x0d,
        ZCL_DATA_TYPE_56_BIT_DATA = 0x0e,
        ZCL_DATA_TYPE_64_BIT_DATA = 0x0f,
        ZCL_DATA_TYPE_Boolean = 0x10,
        ZCL_DATA_TYPE_8_BIT_BITMAP = 0x18,
        ZCL_DATA_TYPE_16_BIT_BITMAP = 0x19,
        ZCL_DATA_TYPE_24_BIT_BITMAP = 0x1a,
        ZCL_DATA_TYPE_32_BIT_BITMAP = 0x1b,
        ZCL_DATA_TYPE_40_BIT_BITMAP = 0x1c,
        ZCL_DATA_TYPE_48_BIT_BITMAP = 0x1d,
        ZCL_DATA_TYPE_56_BIT_BITMAP = 0x1e,
        ZCL_DATA_TYPE_64_BIT_BITMAP = 0x1f,
        ZCL_DATA_TYPE_UINT_8 = 0x20,
        ZCL_DATA_TYPE_UINT_16 = 0x21,
        ZCL_DATA_TYPE_UINT_24 = 0x22,
        ZCL_DATA_TYPE_UINT_32 = 0x23,
        ZCL_DATA_TYPE_UINT_40 = 0x24,
        ZCL_DATA_TYPE_UINT_48 = 0x25,
        ZCL_DATA_TYPE_UINT_56 = 0x26,
        ZCL_DATA_TYPE_UINT_64 = 0x27,
        ZCL_DATA_TYPE_INT_8 = 0x28,
        ZCL_DATA_TYPE_INT_16 = 0x29,
        ZCL_DATA_TYPE_INT_24 = 0x2a,
        ZCL_DATA_TYPE_INT_32 = 0x2b,
        ZCL_DATA_TYPE_INT_40 = 0x2c,
        ZCL_DATA_TYPE_INT_48 = 0x2d,
        ZCL_DATA_TYPE_INT_56 = 0x2e,
        ZCL_DATA_TYPE_INT_64 = 0x2f,
        ZCL_DATA_TYPE_8_BIT_ENUM = 0x30,
        ZCL_DATA_TYPE_16_BIT_ENUM = 0x31,
        ZCL_DATA_TYPE_SEMI_PRECISION = 0x38,
        ZCL_DATA_TYPE_SINGLE_PRECISION = 0x39,
        ZCL_DATA_TYPE_DOUBLE_PRECISION = 0x3a,
        ZCL_DATA_TYPE_OCTET_STRING = 0x41,
        ZCL_DATA_TYPE_CHAR_STRING = 0x42,
        ZCL_DATA_TYPE_LONG_OCTET_STRING = 0x43,
        ZCL_DATA_TYPE_LONG_CHAR_STRING = 0x44,
        ZCL_DATA_TYPE_ARRAY = 0x48,
        ZCL_DATA_TYPE_STRUCT = 0x4c,
        ZCL_DATA_TYPE_SET = 0x50,
        ZCL_DATA_TYPE_BAG = 0x51,
        ZCL_DATA_TYPE_TIME_OF_DATE = 0xe0,
        ZCL_DATA_TYPE_DATE = 0xe1,
        ZCL_DATA_TYPE_UCT_TIME = 0xe2,
        ZCL_DATA_TYPE_CLUSTER_ID = 0xe8,
        ZCL_DATA_TYPE_ATTRIBUTE_ID = 0xe9,
        ZCL_DATA_TYPE_BAC_NET_OID = 0xea,
        ZCL_DATA_TYPE_IEEE_ADDRESS = 0xf0,
        ZCL_DATA_TYPE_128_BIT_SECURITY_KEY = 0xf1,
        ZCL_DATA_TYPE_UNKNOW = 0xff
    };

    int tyZigbeeZcl3Init(void);
    int getZcl3DataType(unsigned char dataType, unsigned char *data, int *realShift);
#ifdef __cplusplus
}
#endif
#endif